## Problem 2

In [1]:
from pyspark import SparkContext
from pyspark.sql import SQLContext
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from matplotlib.colors import ListedColormap


sc= SparkContext()
sqlContext = SQLContext(sc)

In [5]:
sensor_1 = "./sensors1.csv"
sensor_1_df = sqlContext.read.format('csv').options(header='false').load(sensor_1)
df1 = sensor_1_df.toPandas()
df1.shape

(10000, 1001)

In [6]:
Y = df1.loc[:, df1.columns[-1]]
X = df1.drop([df1.columns[-1]], axis=1)

In [7]:
from sklearn.decomposition import PCA
pca = PCA()
df_pca = pca.fit_transform(X=X)
pca.explained_variance_ratio_.round(2)

array([0.48, 0.34, 0.17, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.

## Problem 3

In [23]:
from sklearn.linear_model import LinearRegression
X = df1.loc[:, df1.columns[1:4]]
lr = LinearRegression(fit_intercept=True).fit(X, Y)

In [9]:
lr.coef_

array([10.19226913,  5.26175262, -5.04791382])

In [10]:
lr.intercept_

732.9111297819982

In [11]:
lr.score(X,Y)

0.998047416731351

## Problem 4

In [2]:
sensor_2 = "./sensors2.csv"
sensor_2_df = sqlContext.read.format('csv').options(header='false').load(sensor_2)
df2 = sensor_2_df.toPandas()
Y2 = df2.loc[:, df2.columns[-1]]
X2 = df2.drop([df2.columns[-1]], axis=1)

In [4]:
from sklearn.decomposition import PCA
pca2 = PCA()
df_pca2 = pca2.fit_transform(X=X2)
pca2.explained_variance_ratio_.round(2)

array([0.45, 0.37, 0.18, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ,
       0.  ])

In [19]:
X2 = df2.loc[:, df2.columns[1:4]]

In [24]:
lr.score(X2,Y2)

0.9975426518609404